# --- !Ups
INSERT INTO restaurant (id,name,description,mark,votes,price_range,image_file_name,cover_file_name,category) VALUES (1,'Restaurant 1','You may be a person who loves to cook. You absolutely love to spend time in your kitchen. As a result, you like to outfit your kitchen with the latest and with the best cookware that is available on the market. However, and with that said, if you are like most people in the 21st century, you also live your life on a budget. You simply do not have a great deal of extra money to blow and spend at will. Therefore, with the goal of outfitting your kitchen with the latest, with the best in cookware, you also want to keep your eyes on ways in which you can save money on your cookware purchases. To this end, you might want to focus your attention on the Internet and the World Wide Web, specifically on overstock merchandise sites that are springing up all over the Net.',3,100,10,'/assets/images/restaurant-abe48bd47b7ba31c6934481b714d9dc8.jpg','x','International');
INSERT INTO restaurant (id,name,description,mark,votes,price_range,image_file_name,cover_file_name,category) VALUES (2,'Restaurant 2','You may be a person who loves to cook. You absolutely love to spend time in your kitchen. As a result, you like to outfit your kitchen with the latest and with the best cookware that is available on the market. However, and with that said, if you are like most people in the 21st century, you also live your life on a budget. You simply do not have a great deal of extra money to blow and spend at will. Therefore, with the goal of outfitting your kitchen with the latest, with the best in cookware, you also want to keep your eyes on ways in which you can save money on your cookware purchases. To this end, you might want to focus your attention on the Internet and the World Wide Web, specifically on overstock merchandise sites that are springing up all over the Net.',4,100,10,'/assets/images/restaurant2-9de29a7635b8f54f880f12517e3bec87.jpg','x','Indian | International');
INSERT INTO restaurant (id,name,description,mark,votes,price_range,image_file_name,cover_file_name,category) VALUES (3,'Restaurant 3','You may be a person who loves to cook. You absolutely love to spend time in your kitchen. As a result, you like to outfit your kitchen with the latest and with the best cookware that is available on the market. However, and with that said, if you are like most people in the 21st century, you also live your life on a budget. You simply do not have a great deal of extra money to blow and spend at will. Therefore, with the goal of outfitting your kitchen with the latest, with the best in cookware, you also want to keep your eyes on ways in which you can save money on your cookware purchases. To this end, you might want to focus your attention on the Internet and the World Wide Web, specifically on overstock merchandise sites that are springing up all over the Net.',2,100,10,'/assets/images/restaurant3-90aefa27e1c5b11065c78f14ad8cdf2d.jpg','x','Italian | International');
INSERT INTO restaurant (id,name,description,mark,votes,price_range,image_file_name,cover_file_name,category) VALUES (4,'Restaurant 4','You may be a person who loves to cook. You absolutely love to spend time in your kitchen. As a result, you like to outfit your kitchen with the latest and with the best cookware that is available on the market. However, and with that said, if you are like most people in the 21st century, you also live your life on a budget. You simply do not have a great deal of extra money to blow and spend at will. Therefore, with the goal of outfitting your kitchen with the latest, with the best in cookware, you also want to keep your eyes on ways in which you can save money on your cookware purchases. To this end, you might want to focus your attention on the Internet and the World Wide Web, specifically on overstock merchandise sites that are springing up all over the Net.',2,100,10,'/assets/images/restaurant4-67524742acc849a2faf92c15476f3127.jpg','x','Mediterranean | International');
INSERT INTO restaurant (id,name,description,mark,votes,price_range,image_file_name,cover_file_name,category) VALUES (5,'Restaurant 5','You may be a person who loves to cook. You absolutely love to spend time in your kitchen. As a result, you like to outfit your kitchen with the latest and with the best cookware that is available on the market. However, and with that said, if you are like most people in the 21st century, you also live your life on a budget. You simply do not have a great deal of extra money to blow and spend at will. Therefore, with the goal of outfitting your kitchen with the latest, with the best in cookware, you also want to keep your eyes on ways in which you can save money on your cookware purchases. To this end, you might want to focus your attention on the Internet and the World Wide Web, specifically on overstock merchandise sites that are springing up all over the Net.',5,100,10,'/assets/images/restaurant5-894a242c7707f9d06e2489e5f4b0e4a4.jpg','x','International');
INSERT INTO restaurant (id,name,description,mark,votes,price_range,image_file_name,cover_file_name,category) VALUES (6,'Restaurant 6','You may be a person who loves to cook. You absolutely love to spend time in your kitchen. As a result, you like to outfit your kitchen with the latest and with the best cookware that is available on the market. However, and with that said, if you are like most people in the 21st century, you also live your life on a budget. You simply do not have a great deal of extra money to blow and spend at will. Therefore, with the goal of outfitting your kitchen with the latest, with the best in cookware, you also want to keep your eyes on ways in which you can save money on your cookware purchases. To this end, you might want to focus your attention on the Internet and the World Wide Web, specifically on overstock merchandise sites that are springing up all over the Net.',1,100,10,'/assets/images/restaurant6-82cc6170fdd91516dc035538518a14c2.jpg','x','International');

# --- !Downs
DELETE FROM restaurant WHERE id=1;
DELETE FROM restaurant WHERE id=2;
DELETE FROM restaurant WHERE id=3;
DELETE FROM restaurant WHERE id=4;
DELETE FROM restaurant WHERE id=5;
DELETE FROM restaurant WHERE id=6;